### PR TITLE
Change team layout

### PR DESCRIPTION
**Pull request by mcdoash**
Need to decide on which team layout before merging main-page-redesign to master.

### CODE REVIEW

**Review by Amyffz — APPROVED** [review]

**Comment by mcdoash** [comment]
@AngelaZ0 @Fay-Z Just waiting on your review! Let me know if you have any problems accessing the website. If you'd like you can read a guide on creating reviews [here](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/).

**Comment by mcdoash** [comment]
I've updated the according issue (#4) with comparison photos. 

> Here's the old team layout:

> old_team_layout

> And here's the alternate one:

> central_programming

@Fay-Z @AngelaZ0

**Comment by AngelaZ0** [comment]
I like the alternate one

**Review by AngelaZ0 — APPROVED** [review]
Great

**Comment by mcdoash** [comment]
@AngelaZ0 alright thank you!!! So far the alt one is the general consensus.

**Comment by mcdoash** [comment]
Alright! Now that everyone agrees I'm merging this into main-page-redesign.

**Pull request merged**
