### PR TITLE
Main page responsive

### PR DESCRIPTION
**Pull request by mcdoash**
Everything is finished and ready to go! I've tested it myself on a few devices, but once everything is merged to the master it'd be great if you guys could test it on whatever devices you have.

### CODE REVIEW

**Comment by Amyffz** [comment]
@mcdoash i would, but i dont know how to view it unless you merge it

**Comment by mcdoash** [comment]
Yeah just wait till it's merged to view it. I don't think this pull request really needs review so I'm just going to do it now.

**Comment by Amyffz** [comment]
There is also an awkward long blank after weekly news

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 25, 2017, at 12:05 AM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #17<https://github.com/CentralProgramming/CentralProgramming.github.io/pull/17>.

**Comment by mcdoash** [comment]
Sorry, can you maybe send me a picture of what you're talking about/what device you're on? I'm a bit lost. I'll have to check this in the morning though, sorry.

**Pull request merged**
